### ISSUE TITLE
Table 8: Visitors usual country of residence by Purpose of visit

### ISSUE THREAD

**Issue by remah-arthur** [Vanuatu-National-Statistics-Office/vnso-RAP-tourismStats-materials#35]
Hi Joe,
I run the codes you send for table 8 and came up with the following result:

![image](https://user-images.githubusercontent.com/83197826/135540552-d82f9c02-8a3d-4543-be1a-7d8bceda068c.png)

I think we are missing a code in travel_type_column in the for loop. I have pushed the codes (Tab8_VisUsualResByPOV) to github if you could have a look at it please.

Thanks,
Remah

**Comment by JosephCrispell** [comment]
Hi @remah-arthur,

Thanks for spotting this, there was a small mistake in the code I provided, which meant the tables with percentages weren't being added to the final summary table.

I've now updated the [pivot_wider_14-09-21.R](https://github.com/Vanuatu-National-Statistics-Office/vnso-R-training-materials/blob/master/examples/pivot_wider_14-09-21.R) script, which now gives:
![image](https://user-images.githubusercontent.com/17436210/135628307-a6666f04-fa38-4794-8326-7044e64818da.png)

On the `Tab8_VisUsualResByPOV` branch of the `vnso-RAP-tourismStats-materials` repository I can't see the code that you have added. I also notice that a lot of the trades code is present, which might be worth removing and only adding if it is used - this is something we can pick in our Tuesday discussions when the census work has been completed.

Let me know if the updated code and thanks again for flagging.

Joe

**Comment by remah-arthur** [comment]
Hi Joe,

Thank you for the codes, it finally worked and I arranged the columns in the final format. I will push the final codes through today. Regarding the trades codes, i do not have any trades codes in the branch i am working on (no error too) but will check again.

Thank you once again, really appreciate it. 
Kind regards,
Remah

**Comment by JosephCrispell** [comment]
HI @remah-arthur,

Excellent, thanks for letting me know 👍.

Joe
